#!/bin/bash
ver=0.3.0
#
# customizepkg => modify PKGBUILD before building
#
# Copyright (C) 2007-2013  Wain (original) & Doug Newgard (scripting ver)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

NAME=`basename $0`
CONFIGDIR="/etc/$NAME.d"

usage() {
  echo "$NAME - version $ver"
  echo
  echo "Without any options, $NAME reads the PKGBUILD in the current directory and shows a diff between the original PKGBUILD and the customized PKGBUILD."
  echo "$NAME-scripting reads scripts in $CONFIGDIR"
  echo
  echo "usage: $NAME <option>"
  echo
  echo "$NAME --version, -V       shows version"
  echo "$NAME --help,    -h       shows this help"
  echo "$NAME --modify,  -m       apply the modification to the PKGBUILD file"
  echo "$NAME --vimdiff, -v       show diff between customised file and original file with vimdiff"

  exit 0
}

version() {
  echo "$NAME-scripting - version $ver"

  exit 0
}

########################
# Main Program
VIMDIFF=0
MODIFY=0

while [[ "$#" -ne "0" ]]; do
  case $1 in
    -h | --help) usage ;;
    -V | --version) version ;;
    -m | --modify) MODIFY=1 ;;
    -v | --vimdiff) VIMDIFF=1 ;;
    *) echo -e "Invalid option $1\n" && usage ;;
  esac
  shift
done

if [[ ! -r ./PKGBUILD ]]; then
  echo "PKGBUILD not found"
  exit 1
fi

source ./PKGBUILD || exit 1

if [[ $pkgroot ]]; then
  pkgname=$pkgroot
elif [[ $(declare -p variable-name 2> /dev/null | grep -q 'declare \-a') ]]; then
  pkgname=$pkgname[1]
fi

if [[ ! -r "$CONFIGDIR/$pkgname" ]]; then
  echo "no script found for $pkgname in $CONFIGDIR/"
  exit 1
fi

cp ./PKGBUILD ./PKGBUILD.custom
cp ./$install ./$install.custom

"$CONFIGDIR/$pkgname" "$PWD/PKGBUILD.custom" "$PWD/$install.custom" || exit 1

if [[ $VIMDIFF -eq 1 ]]; then
  vim -d ./PKGBUILD ./PKGBUILD.custom
  vim -d "./$install" "./$install.custom"
else
  diff -Nau ./PKGBUILD ./PKGBUILD.custom
  diff -Nau "./$install" "./$install.custom"
fi

if [[ $MODIFY -eq 1 ]]; then
  cp ./PKGBUILD ./PKGBUILD.original
  mv ./PKGBUILD.custom ./PKGBUILD
  cp "./$install" "./$install.original"
  mv "./$install.custom" "./$install"
fi

exit 0
